---
functional:
  - Пользователь должен иметь возможность авторизоваться
  - Пользователь должен иметь возможность зарегестрироваться
  - Пользователь должен иметь возможность восстановления пароля по email
  - Пользователь должен иметь возможность создавать игры c другими пользователями/друзьями/ботами
  - Пользователь должен иметь возможность играть с другими пользователями/друзьями/ботами
  - Пользователь должен иметь возможность создавать турнир  
  - Пользователь должен иметь возможность создавать игры без регистрации
  - Пользователь должен иметь возможность использовать различные языки программирования
  - Пользователь должен иметь возможность настройки профиля
  - Пользователь должен иметь возможность наблюдать за игрой других пользователей в реальном времени
  - Пользователь должен иметь возможность сортировки других пользователей в таблице рейтинга
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен соблюдать местное законодательство о персональных данных (GDPR, CCPA, №154-ФЗ "О персональных данных")
  - Пользователь может авторизоваться через аккаунт Telegram
  - Пользователь может авторизоваться через аккаунт Hexlet
  - Пользователь может прилинковать аккаунт почты к своему аккаунту Github
  - Пользователь может изменить email аккаунта

