---
functional:
  - Пользователь должен иметь возможность авторизоваться
  - Пользователь должен иметь возможность зарегестрироваться
  - Пользователь должен иметь возможность создавать игры c ботом
  - Пользователь должен иметь возможность играть с другими пользователями/друзьями
  - Пользователь должен иметь возможность создавать турнир
  - Пользователь должен иметь возможность создавать игры без регистрации
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен соблюдать местное законодательство о персональных данных (GDPR, CCPA, №154-ФЗ "О персональных данных")
#доделать
#документация https://github.com/hexlet-codebattle/codebattle/wiki
